### ISSUE TITLE
No longer working

### ISSUE THREAD

**Issue by maxrpg123** [skyllo/docker-build-retropie-image#1]
Hi,

I have tried and tried to get this to work but it keeps failing.

I'm using the latest download of docker and I managed to fix the issue with zesty when running your script but now I get the following error:

update-binfmts: warning: Couldn't mount the binfmt_misc filesystem on /proc/sys/fs/binfmt_misc

Can you please help me get this working?

Maybe needs slightly updating.

Thank you.

**Comment by mpalpha** [comment]
this could be relevant https://stackoverflow.com/questions/54951262/binfmt-misc-problems-in-ubuntu18-04-under-docker
